### ISSUE TITLE
alertlogic/ercloud erlcloud_aws:sign_v4 compatibility

### ISSUE THREAD

**Issue by zacharyfox** [alertlogic/erlcloud#11]
It appears that erlcloud_aws:sign_v4 in this fork is not compatible with gleber/erlcloud.

I'm trying to test erlcloud_kms from EligibleAPI/erlcloud and it will not currently work with our fork. I'm unsure how I should proceed.

**Comment by motobob** [comment]
@zacharyfox this fork is not compatible to upstream long before sign_v4 and that's the problem i deal with too and committed to solve really soon. 
If you want to test KMS addition with some features of yours in us-east-1/eu-west-2 feel free to use upstream or EligibleAPI fork. SigV4 should not really change anything. 

Secondly, i'm not sure erlcloud_kms_impl:request/3 is that fork is done right since it re-implements some things with headers and re-tries. I'll review that later.

If that does not work for you, i see no other option 
- resolve conflits manually 
- wait till that gets merged to upstream and ask me to merge the upsteam

**Comment by motobob** [comment]
closing this as we found a way around.  and I will resume work on merging our stuff into upstream so not to have such issues in future
